[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip R7FA6E2BB --chip-description-path ../../../probe-rs/probe-rs/targets/RA6E2_Series.yaml"

[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-L.",
]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "trace"
