pub use embassy_hal_internal::interrupt::{InterruptExt, Priority};

// Note: RA uses ICU (Interrupt Controller Unit) with IELSR registers
// for event-to-IRQ mapping, unlike STM32's fixed interrupt vectors.
// The irq_bindings.rs generated by build.rs handles this mapping.

pub trait Event {
    const ID: u16;
    const IRQ_NUMBERS: &'static [u8];
}

// Note: InterruptRegistry removed - RA doesn't use the STM32 typelevel pattern.
// Instead, irq_bindings.rs generates handlers that are mapped via ICU IELSR.

pub trait Handler<E: Event> {
    unsafe fn on_interrupt();
}

pub unsafe trait Binding<E: Event, H: Handler<E>> {}

#[inline]
fn icu() -> ra_metapac::icu::Icu {
    ra_metapac::ICU
}

/// Clear the ICU IELSR interrupt request flag using fieldset accessors.
#[inline]
pub(crate) fn clear_icu_ir(irq: usize) {
    let icu = icu();
    icu.ielsr(irq).modify(|w| w.set_ir(false));
    let _ = icu.ielsr(irq).read();
}


pub mod events {
    use super::Event;

    macro_rules! event_structs {
        ($(($name:ident, $id:tt, ($($irq_num:tt),*)),)*) => {
            $(
                pub struct $name;
                impl Event for $name {
                    const ID: u16 = $id;
                    const IRQ_NUMBERS: &'static [u8] = &[$($irq_num),*];
                }
            )*
        };
    }

    crate::pac::foreach_event!(event_structs);
}

/// Const function to check if an IRQ number is valid for an event.
/// Returns true if the event has no restrictions (empty list) or if the IRQ is in the list.
pub const fn is_valid_irq_for_event(irq_numbers: &[u8], irq: u8) -> bool {
    // Empty list means unrestricted
    if irq_numbers.is_empty() {
        return true;
    }
    // Check if IRQ is in the allowed list
    let mut i = 0;
    while i < irq_numbers.len() {
        if irq_numbers[i] == irq {
            return true;
        }
        i += 1;
    }
    false
}

/// Bind event interrupts to handlers.
///
/// Usage:
/// ```ignore
/// bind_interrupts!(struct Irqs {
///     Gpt0CounterOverflow => TimerHandler;
///     Gpt0CaptureCompareA => TimerHandler;
/// });
/// ```
///
/// Note: Event-to-IEL slot allocation is performed by the build script using the
/// per-family `Event::IRQ_NUMBERS` constraints from the PAC metadata.
#[macro_export]
macro_rules! bind_interrupts {
    ($vis:vis struct $name:ident {
        $(
            $event:ident => $($handler:ty),+;
        )*
    }) => {
        $vis struct $name;

        $(
            const _: () = {
                #[export_name = concat!("__embassy_ra_event_", stringify!($event))]
                pub unsafe extern "C" fn handler() {
                    $(
                        <$handler as $crate::interrupt::Handler<$crate::interrupt::events::$event>>::on_interrupt();
                    )+
                }
            };

            $crate::bind_interrupts!(@inner
                $(unsafe impl $crate::interrupt::Binding<$crate::interrupt::events::$event, $handler> for $name {})+
            );
        )*
    };
    (@inner $($t:tt)*) => {
        $($t)*
    };
}

