use std::collections::BTreeMap;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use ra_metapac::metadata::{self, Event};

// ============================================================================
// EVENT SELECTION (ENV-DRIVEN)
// ============================================================================

/// Convert metadata event names (e.g., "GPT0_COUNTER_OVERFLOW") to PAC-style CamelCase (e.g., "Gpt0CounterOverflow")
fn event_symbol_name(event_name: &str) -> String {
    event_name
        .split('_')
        .filter(|s| !s.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + &chars.as_str().to_ascii_lowercase(),
                None => String::new(),
            }
        })
        .collect::<Vec<String>>()
        .join("")
}

/// Collect additional events from EMBASSY_RA_EVENTS.
/// Accepts metadata names (e.g., "GPT0_COUNTER_OVERFLOW") or PAC symbols (e.g., "Gpt0CounterOverflow").
fn get_env_events() -> Vec<&'static Event> {
    let mut names: Vec<String> = Vec::new();

    if let Ok(list) = env::var("EMBASSY_RA_EVENTS") {
        names.extend(
            list.split(|c: char| c == ',' || c.is_whitespace())
                .filter(|s| !s.is_empty())
                .map(|s| s.to_string()),
        );
    }

    if names.is_empty() {
        return Vec::new();
    }

    metadata::METADATA
        .events
        .iter()
        .filter(|event| {
            let symbol = event_symbol_name(event.name);
            names.iter().any(|n| n == event.name || n == &symbol)
        })
        .collect()
}

fn find_event_by_name(name: &str) -> Option<&'static Event> {
    metadata::METADATA.events.iter().find(|event| event.name == name)
}

fn get_time_driver_events(time_driver: Option<&str>) -> Vec<&'static Event> {
    let Some(time_driver) = time_driver else {
        return Vec::new();
    };

    let int = format!("{}_INT", time_driver);
    let cmpa = format!("{}_COMPARE_A", time_driver);
    let mut events = Vec::new();
    if let Some(event) = find_event_by_name(&int) {
        events.push(event);
    }
    if let Some(event) = find_event_by_name(&cmpa) {
        events.push(event);
    }
    events
}

// ============================================================================
// BUILD SCRIPT MAIN
// ============================================================================

fn main() {
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    println!("cargo:rerun-if-env-changed=EMBASSY_RA_EVENTS");

    let chip_name = env::vars()
        .map(|(a, _)| a)
        .filter(|x| x.starts_with("CARGO_FEATURE_R7") || x.starts_with("CARGO_FEATURE_R8"))
        .next()
        .map(|x| x.strip_prefix("CARGO_FEATURE_").unwrap().to_ascii_lowercase().replace('_', "-"));

    if let Some(chip_name) = chip_name {
        println!("cargo:rustc-cfg={}", chip_name);
        println!("cargo:rustc-cfg=ra");
        
        // Use family from the PAC METADATA (e.g., "ra6e2", "ra2e1", "ra4m1")
        // This is generated by ra-metapac-gen from the chip's family field
        let family = metadata::METADATA.family;
        println!("cargo:rustc-cfg={}", family);
        
        // Tell Cargo to expect our custom cfg values
        println!("cargo::rustc-check-cfg=cfg(ra)");
        // Family cfgs - comprehensive list of all RA families
        for family in &[
            // RA0 series
            "ra0e1", "ra0e2",
            // RA2 series
            "ra2a1", "ra2a2", "ra2e1", "ra2e2", "ra2e3", "ra2l1", "ra2l2", "ra2t1",
            // RA4 series
            "ra4c1", "ra4e1", "ra4e2", "ra4l1", "ra4m1", "ra4m2", "ra4m3", "ra4t1", "ra4w1",
            // RA6 series
            "ra6e1", "ra6e2", "ra6m1", "ra6m2", "ra6m3", "ra6m4", "ra6m5", "ra6t1", "ra6t2", "ra6t3",
            // RA8 series
            "ra8d1", "ra8e1", "ra8e2", "ra8m1", "ra8p1", "ra8t1",
        ] {
            println!("cargo::rustc-check-cfg=cfg({})", family);
        }

        // Handle time driver selection
        let time_driver = get_time_driver_singleton();
        if let Some(ref driver) = time_driver {
            println!("cargo:rustc-cfg=time_driver_{}", driver.to_lowercase());
        }
        // Declare all possible time driver cfgs
        for i in 0..=1 {
            println!("cargo::rustc-check-cfg=cfg(time_driver_agt{})", i);
        }

        // Declare AGT counter-width cfgs so rustc does not warn about them.
        println!("cargo::rustc-check-cfg=cfg(agt_counter_16bit)");
        println!("cargo::rustc-check-cfg=cfg(agt_counter_32bit)");

        // If an AGT peripheral is the time driver, emit the counter-width cfg
        // based on the `version` field in the chip metadata ("16bits"/"32bits").
        if let Some(ref driver) = time_driver {
            if driver.starts_with("AGT") {
                for p in metadata::METADATA.peripherals {
                    if p.name == driver.as_str() && p.kind == "agt" {
                        match p.version {
                            "16bits" => println!("cargo:rustc-cfg=agt_counter_16bit"),
                            "32bits" => println!("cargo:rustc-cfg=agt_counter_32bit"),
                            v => panic!("unknown AGT version '{}' for peripheral '{}'", v, p.name),
                        }
                        break;
                    }
                }
            }
        }

        generate_memory_x(&out);
        generate_option_bytes(&out, family);
        generate_interrupt_bindings(&out, time_driver.as_deref());
        generate_peripherals(&out, time_driver.as_deref());
    }

    println!("cargo:rerun-if-changed=build.rs");
}

/// Get the selected time driver peripheral name
fn get_time_driver_singleton() -> Option<String> {
    for i in 0..=1 {
        let feature = format!("CARGO_FEATURE_TIME_DRIVER_AGT{}", i);
        if env::var(&feature).is_ok() {
            return Some(format!("AGT{}", i));
        }
    }
    None
}

/// Generate peripherals module
fn generate_peripherals(out: &PathBuf, time_driver: Option<&str>) {
    let mut singletons: Vec<String> = Vec::new();
    
    // Add all peripherals from metadata
    for p in metadata::METADATA.peripherals {
        singletons.push(p.name.to_string());
    }
    
    // Collect GPIO pins with parsed port/pin numbers
    // Pin names are like "P100" -> port 1, pin 0
    // "P008" -> port 0, pin 8
    let mut pins: Vec<(String, u8, u8)> = Vec::new();
    for pin in metadata::METADATA.pins {
        let name = pin.name.to_string();
        // Parse port and pin from name like "P100" -> port 1, pin 0
        // Format is Pxyz where x is port, yz is pin (2 digits)
        if name.len() >= 4 && name.starts_with('P') {
            if let Ok(num) = name[1..].parse::<u16>() {
                let port = (num / 100) as u8;
                let pin_num = (num % 100) as u8;
                pins.push((name.clone(), port, pin_num));
                singletons.push(name);
            }
        }
    }
    
    // Generate the peripherals.rs file
    let mut code = String::new();
    writeln!(code, "// Auto-generated peripherals module").unwrap();
    writeln!(code, "// DO NOT EDIT - generated by build.rs").unwrap();
    writeln!(code).unwrap();
    
    // Generate singleton list for peripherals_definition! macro
    let singleton_list = singletons.join(", ");
    writeln!(code, "embassy_hal_internal::peripherals_definition!({});", singleton_list).unwrap();
    writeln!(code).unwrap();
    
    // Generate peripherals struct (excluding time driver singleton)
    let struct_singletons: Vec<_> = singletons.iter()
        .filter(|s| time_driver.map_or(true, |td| *s != td))
        .cloned()
        .collect();
    let struct_singleton_list = struct_singletons.join(", ");
    writeln!(code, "embassy_hal_internal::peripherals_struct!({});", struct_singleton_list).unwrap();
    writeln!(code).unwrap();
    
    // Generate pin trait implementations
    writeln!(code, "// Pin trait implementations").unwrap();
    writeln!(code, "#[cfg(feature = \"gpio\")]").unwrap();
    writeln!(code, "mod pin_impls {{").unwrap();
    writeln!(code, "    use crate::gpio::{{Pin, AnyPin, sealed}};").unwrap();
    writeln!(code, "    use crate::peripherals;").unwrap();
    writeln!(code).unwrap();
    
    for (name, port, pin) in &pins {
        writeln!(code, "    impl Pin for peripherals::{} {{}}", name).unwrap();
        writeln!(code, "    impl sealed::Pin for peripherals::{} {{", name).unwrap();
        writeln!(code, "        #[inline]").unwrap();
        writeln!(code, "        fn pin_port(&self) -> u16 {{").unwrap();
        writeln!(code, "            ({} as u16) * 16 + ({} as u16)", port, pin).unwrap();
        writeln!(code, "        }}").unwrap();
        writeln!(code, "    }}").unwrap();
        writeln!(code).unwrap();
        writeln!(code, "    impl From<peripherals::{}> for AnyPin {{", name).unwrap();
        writeln!(code, "        fn from(_: peripherals::{}) -> Self {{", name).unwrap();
        writeln!(code, "            unsafe {{ Self::new({}, {}) }}", port, pin).unwrap();
        writeln!(code, "        }}").unwrap();
        writeln!(code, "    }}").unwrap();
        writeln!(code).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code, "#[cfg(feature = \"gpio\")]").unwrap();
    writeln!(code, "#[allow(unused_imports)]").unwrap();
    writeln!(code, "pub use pin_impls::*;").unwrap();
    
    fs::write(out.join("peripherals.rs"), code).unwrap();
}




/// Generate memory.x linker script
fn generate_memory_x(out: &PathBuf) {
    let mut memory_x = String::new();

    let flash_region = metadata::METADATA.memory.iter().find(|r| r.name == "FLASH").unwrap();
    let mut overlaps = Vec::new();
    for region in metadata::METADATA.memory {
        if region.name.starts_with("OPTION_SETTING_") {
            if region.address >= flash_region.address && region.address < flash_region.address + flash_region.size {
                overlaps.push(region);
            }
        }
    }

    if !overlaps.is_empty() {
        let last_region = overlaps.iter().max_by_key(|r| r.address + r.size).unwrap();
        let end_addr = last_region.address + last_region.size;
        writeln!(memory_x, "_stext = 0x{:08x};", end_addr).unwrap();
    }

    writeln!(memory_x, "MEMORY").unwrap();
    writeln!(memory_x, "{{").unwrap();

    for region in metadata::METADATA.memory {
        let size_str = if region.size >= 1024 && region.size % 1024 == 0 {
            format!("{}K", region.size / 1024)
        } else {
            format!("{}", region.size)
        };

        writeln!(
            memory_x,
            "    {} : ORIGIN = 0x{:08x}, LENGTH = {}",
            region.name, region.address, size_str
        )
        .unwrap();
    }
    writeln!(memory_x, "}}").unwrap();

    writeln!(memory_x, "SECTIONS").unwrap();
    writeln!(memory_x, "{{").unwrap();

    for region in metadata::METADATA.memory {
        if region.name.starts_with("OPTION_SETTING_") {
            // Use the full lowercased region name as the section name so that it
            // matches the `#[link_section = ".option_setting_*"]` attributes used
            // in `option_bytes.rs`. Previously the prefix was stripped, creating a
            // mismatch that silently dropped all option-byte statics from flash.
            let section_name = region.name.to_lowercase();
            if overlaps.iter().any(|o| o.name == region.name) {
                writeln!(
                    memory_x,
                "    .{} 0x{:08x} : {{ KEEP(*(.{})) }} > {}",
                section_name, region.address, section_name, region.name
                )
                .unwrap();
            } else {
                writeln!(memory_x, "    .{} : {{ KEEP(*(.{})) }} > {}", section_name, section_name, region.name)
                    .unwrap();
            }
        }
    }
    writeln!(memory_x, "}}").unwrap();

    fs::write(out.join("memory.x"), memory_x).unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=memory.x");
}

/// Get enabled peripheral configs based on Cargo features
/// Collect all required events from enabled peripherals
fn get_required_events(time_driver: Option<&str>) -> Vec<&'static Event> {
    let mut events = get_env_events();
    events.extend(get_time_driver_events(time_driver));
    events
}

/// Allocates IRQ slots to events, respecting group constraints
fn allocate_irq_slots(required_events: &[&Event]) -> BTreeMap<&'static str, u8> {
    let mut allocations: BTreeMap<&'static str, u8> = BTreeMap::new();
    let mut used_slots: Vec<bool> = vec![false; metadata::METADATA.interrupt_count];

    // First pass: allocate events with restricted slots (grouped events)
    for event in required_events {
        if !event.irq_slots.is_empty() {
            // Find first available slot from the allowed list
            for &slot in event.irq_slots {
                if !used_slots[slot as usize] {
                    used_slots[slot as usize] = true;
                    allocations.insert(event.name, slot);
                    break;
                }
            }
        }
    }

    // Second pass: allocate events with unrestricted slots
    for event in required_events {
        if allocations.contains_key(event.name) {
            continue; // Already allocated
        }
        if event.irq_slots.is_empty() {
            // Find first available slot
            for (slot, used) in used_slots.iter_mut().enumerate() {
                if !*used {
                    *used = true;
                    allocations.insert(event.name, slot as u8);
                    break;
                }
            }
        }
    }

    allocations
}

/// Generates the interrupt binding code
fn generate_interrupt_bindings(out_dir: &PathBuf, time_driver: Option<&str>) {
    let required_events = get_required_events(time_driver);
    validate_time_driver_events(time_driver, &required_events);
    let allocations = allocate_irq_slots(&required_events);
    let mut unique_events: BTreeMap<&'static str, &'static Event> = BTreeMap::new();
    for event in &required_events {
        unique_events.entry(event.name).or_insert(*event);
    }

    let mut code = String::new();
    writeln!(code, "// Auto-generated interrupt bindings").unwrap();
    writeln!(code, "// DO NOT EDIT - generated by build.rs").unwrap();
    writeln!(code).unwrap();

    // Generate event-to-IRQ mapping constants
    writeln!(code, "/// Auto-allocated IRQ slots for events").unwrap();
    writeln!(code, "pub mod irq_allocations {{").unwrap();
    for (event_name, irq_slot) in &allocations {
        let const_name = event_name.to_uppercase();
        writeln!(code, "    /// IRQ slot for {} event", event_name).unwrap();
        writeln!(code, "    pub const {}_IRQ: u8 = {};", const_name, irq_slot).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Generate event IDs
    writeln!(code, "/// Event IDs for ICU IELSR programming").unwrap();
    writeln!(code, "pub mod event_ids {{").unwrap();
    for event in unique_events.values() {
        let const_name = event.name.to_uppercase();
        writeln!(code, "    pub const {}: u16 = {};", const_name, event.id).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Generate externs for event handler symbols
    writeln!(code, "extern \"C\" {{").unwrap();
    for event in unique_events.values() {
        let symbol = event_symbol_name(event.name);
        writeln!(code, "    fn __embassy_ra_event_{}();", symbol).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Generate IEL interrupt handlers for each required event
    for event in unique_events.values() {
        if let Some(&slot) = allocations.get(event.name) {
            let symbol = event_symbol_name(event.name);
            writeln!(code, "/// Interrupt handler for {} (IEL{})", event.name, slot).unwrap();
            writeln!(code, "#[no_mangle]").unwrap();
            writeln!(code, "#[allow(non_snake_case)]").unwrap();
            writeln!(code, "pub unsafe extern \"C\" fn IEL{}() {{", slot).unwrap();
            writeln!(code, "    __embassy_ra_event_{}();", symbol).unwrap();
            writeln!(code, "}}").unwrap();
            writeln!(code).unwrap();
        }
    }

    fs::write(out_dir.join("irq_bindings.rs"), code).unwrap();
}

fn validate_time_driver_events(time_driver: Option<&str>, required_events: &[&Event]) {
    let Some(time_driver) = time_driver else {
        return;
    };

    let int = format!("{}_INT", time_driver);
    let cmpa = format!("{}_COMPARE_A", time_driver);
    let has_int = required_events.iter().any(|e| e.name == int);
    let has_cmpa = required_events.iter().any(|e| e.name == cmpa);
    if has_int && has_cmpa {
        return;
    }
    panic!(
        "Missing time driver events for {}. Need {} and {}.",
        time_driver, int, cmpa
    );
}

fn generate_option_bytes(out: &PathBuf, family: &str) {
    let all_hoco = ["24mhz", "32mhz", "48mhz", "64mhz", "16mhz", "18mhz", "20mhz"];
    for f in &all_hoco {
        println!(
            "cargo:rerun-if-env-changed=CARGO_FEATURE_HOCO_{}",
            f.to_uppercase().replace("MHZ", "MHZ")
        );
    }

    let selected: Vec<&str> = all_hoco
        .iter()
        .filter(|&&f| {
            let var = format!("CARGO_FEATURE_HOCO_{}", f.to_uppercase().replace("MHZ", "MHZ"));
            env::var(var).is_ok()
        })
        .copied()
        .collect();

    if selected.len() > 1 {
        panic!(
            "Only one hoco-* feature may be selected at a time, but got: {:?}",
            selected
        );
    }

    for f in &all_hoco {
        println!(
            "cargo::rustc-check-cfg=cfg(hoco_{})",
            f.replace("mhz", "mhz")
        );
    }

    let (ofs1, tz, freq_str) = match family {
        "ra2e1" | "ra2e2" | "ra2l1" | "ra2e3" | "ra2l2" | "ra2a1" | "ra2a2" | "ra2t1" => {
            let f = selected.first().copied().unwrap_or("48mhz");
            let v = match f {
                "24mhz" => 0xFFFF8FFFu32,
                "32mhz" => 0xFFFFAFFFu32,
                "48mhz" => 0xFFFFCFFFu32,
                "64mhz" => 0xFFFFDFFFu32,
                _ => panic!("hoco-{} is not valid for RA2 (valid: 24/32/48/64 MHz)", f),
            };
            (v, false, f)
        }
        "ra4m1" | "ra4e1" | "ra4w1" | "ra4e2" | "ra4m2" | "ra4m3" | "ra4c1" | "ra4l1"
        | "ra4t1" | "ra6m1" | "ra6m2" | "ra6m3" | "ra6e1" | "ra6t1" | "ra6t2" | "ra6t3" => {
            let f = selected.first().copied().unwrap_or("48mhz");
            let v = match f {
                "24mhz" => 0xFFFFF9FFu32,
                "32mhz" => 0xFFFFFBFFu32,
                "48mhz" => 0xFFFFFDFFu32,
                "64mhz" => 0xFFFFFFFFu32,
                _ => panic!(
                    "hoco-{} is not valid for RA4/RA6 non-TZ (valid: 24/32/48/64 MHz)",
                    f
                ),
            };
            (v, false, f)
        }
        "ra6e2" | "ra6m4" | "ra6m5" => {
            let f = selected.first().copied().unwrap_or("20mhz");
            let v = match f {
                "16mhz" => 0xFFFFF9FFu32,
                "18mhz" => 0xFFFFFBFFu32,
                "20mhz" => 0xFFFFFDFFu32,
                _ => panic!(
                    "hoco-{} is not valid for RA6 TrustZone (valid: 16/18/20 MHz)",
                    f
                ),
            };
            (v, true, f)
        }
        "ra8m1" | "ra8d1" | "ra8e1" | "ra8t1" | "ra8e2" | "ra8p1" => {
            let f = selected.first().copied().unwrap_or("20mhz");
            let v = match f {
                "16mhz" => 0xFFFFF1FFu32,
                "18mhz" => 0xFFFFF3FFu32,
                "20mhz" => 0xFFFFF5FFu32,
                _ => panic!("hoco-{} is not valid for RA8 (valid: 16/18/20 MHz)", f),
            };
            (v, false, f)
        }
        _ => (0xFFFF_FFFFu32, false, "20mhz"),
    };

    let hoco_variant = match freq_str {
        "16mhz" => "Mhz16",
        "18mhz" => "Mhz18",
        "20mhz" => "Mhz20",
        "24mhz" => "Mhz24",
        "32mhz" => "Mhz32",
        "48mhz" => "Mhz48",
        "64mhz" => "Mhz64",
        _ => "Mhz20",
    };

    let mut code = String::new();
    writeln!(code, "// Auto-generated by build.rs — do not edit").unwrap();
    writeln!(code, "// Family: {}", family).unwrap();
    writeln!(code).unwrap();
    writeln!(
        code,
        "pub(crate) const EMBASSY_RA_HOCO_FREQ: crate::system::HocoFreq = crate::system::HocoFreq::{};",
        hoco_variant
    ).unwrap();
    writeln!(code).unwrap();
    writeln!(code, "#[link_section = \".option_setting_ofs0\"]").unwrap();
    writeln!(code, "#[used]").unwrap();
    writeln!(code, "static __EMBASSY_RA_OFS0: u32 = 0xFFFF_FFFFu32;").unwrap();
    writeln!(code).unwrap();

    if tz {
        writeln!(code, "#[link_section = \".option_setting_ofs1_sec\"]").unwrap();
        writeln!(code, "#[used]").unwrap();
        writeln!(code, "static __EMBASSY_RA_OFS1: u32 = 0x{:08X}u32;", ofs1).unwrap();
        writeln!(code).unwrap();
        writeln!(code, "#[link_section = \".option_setting_bps_sec\"]").unwrap();
        writeln!(code, "#[used]").unwrap();
        writeln!(code, "static __EMBASSY_RA_BPS_SEC: u32 = 0xFFFF_FFFFu32;").unwrap();
        writeln!(code).unwrap();
        writeln!(code, "#[link_section = \".option_setting_pbps_sec\"]").unwrap();
        writeln!(code, "#[used]").unwrap();
        writeln!(code, "static __EMBASSY_RA_PBPS_SEC: u32 = 0xFFFF_FFFFu32;").unwrap();
    } else {
        writeln!(code, "#[link_section = \".option_setting_ofs1\"]").unwrap();
        writeln!(code, "#[used]").unwrap();
        writeln!(code, "static __EMBASSY_RA_OFS1: u32 = 0x{:08X}u32;", ofs1).unwrap();
    }

    fs::write(out.join("option_bytes.rs"), code).unwrap();
}
