use std::collections::BTreeMap;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::PathBuf;

use ra_metapac::metadata::{self, Event, Peripheral};

// ============================================================================
// PERIPHERAL IRQ CONFIGURATION
// ============================================================================

/// Defines a peripheral's interrupt configuration
struct PeripheralIrqConfig {
    /// Cargo feature that enables this peripheral (without CARGO_FEATURE_ prefix)
    feature: &'static str,
    /// Peripheral name to match (e.g., "GPT0", "SCI1", "IIC0")
    peripheral_name: &'static str,
    /// Signal names this peripheral needs (e.g., ["COUNTER_OVERFLOW", "CAPTURE_COMPARE_A"])
    signals: &'static [&'static str],
    /// Handler function to call for these events
    handler: &'static str,
}

/// GPT Timer configurations (for time driver)
const GPT_CONFIGS: &[PeripheralIrqConfig] = &[
    PeripheralIrqConfig {
        feature: "TIME_DRIVER_GPT0",
        peripheral_name: "GPT0",
        signals: &["COUNTER_OVERFLOW", "CAPTURE_COMPARE_A"],
        handler: "crate::time_driver::on_interrupt",
    },
    PeripheralIrqConfig {
        feature: "TIME_DRIVER_GPT1",
        peripheral_name: "GPT1",
        signals: &["COUNTER_OVERFLOW", "CAPTURE_COMPARE_A"],
        handler: "crate::time_driver::on_interrupt",
    },
    PeripheralIrqConfig {
        feature: "TIME_DRIVER_GPT2",
        peripheral_name: "GPT2",
        signals: &["COUNTER_OVERFLOW", "CAPTURE_COMPARE_A"],
        handler: "crate::time_driver::on_interrupt",
    },
    PeripheralIrqConfig {
        feature: "TIME_DRIVER_GPT3",
        peripheral_name: "GPT3",
        signals: &["COUNTER_OVERFLOW", "CAPTURE_COMPARE_A"],
        handler: "crate::time_driver::on_interrupt",
    },
];

/// Get all peripheral configurations
fn get_all_peripheral_configs() -> Vec<&'static PeripheralIrqConfig> {
    let mut configs: Vec<&'static PeripheralIrqConfig> = Vec::new();
    
    // Add GPT configs
    configs.extend(GPT_CONFIGS.iter());
    
    // Add more peripheral configs here as needed:
    // configs.extend(SCI_CONFIGS.iter());
    // configs.extend(IIC_CONFIGS.iter());
    // configs.extend(SPI_CONFIGS.iter());
    
    configs
}

/// Find the peripheral by name from metadata
fn find_peripheral(name: &str) -> Option<&'static Peripheral> {
    metadata::METADATA.peripherals.iter().find(|p| p.name == name)
}

/// Find events for a peripheral config using the peripheral's interrupt list
fn find_events_for_config(config: &PeripheralIrqConfig) -> Vec<&'static Event> {
    let peripheral = match find_peripheral(config.peripheral_name) {
        Some(p) => p,
        None => return Vec::new(),
    };
    
    // Build event names from peripheral name + signal (e.g., "GPT0" + "COUNTER_OVERFLOW" -> "GPT0_COUNTER_OVERFLOW")
    let event_names: Vec<String> = peripheral.interrupts
        .iter()
        .filter(|signal| config.signals.contains(signal))
        .map(|signal| format!("{}_{}", peripheral.name, signal))
        .collect();
    
    // Find the corresponding Event entries with full metadata
    metadata::METADATA.events
        .iter()
        .filter(|event| event_names.iter().any(|name| name == event.name))
        .collect()
}

// ============================================================================
// BUILD SCRIPT MAIN
// ============================================================================

fn main() {
    let out = PathBuf::from(env::var_os("OUT_DIR").unwrap());

    let chip_name = env::vars()
        .map(|(a, _)| a)
        .filter(|x| x.starts_with("CARGO_FEATURE_R7") || x.starts_with("CARGO_FEATURE_R8"))
        .next()
        .map(|x| x.strip_prefix("CARGO_FEATURE_").unwrap().to_ascii_lowercase().replace('_', "-"));

    if let Some(chip_name) = chip_name {
        println!("cargo:rustc-cfg={}", chip_name);
        println!("cargo:rustc-cfg=ra");
        
        // Use family from the PAC METADATA (e.g., "ra6e2", "ra2e1", "ra4m1")
        // This is generated by ra-metapac-gen from the chip's family field
        let family = metadata::METADATA.family;
        println!("cargo:rustc-cfg={}", family);
        
        // Tell Cargo to expect our custom cfg values
        println!("cargo::rustc-check-cfg=cfg(ra)");
        // Family cfgs - comprehensive list of all RA families
        for family in &[
            // RA0 series
            "ra0e1", "ra0e2",
            // RA2 series
            "ra2a1", "ra2a2", "ra2e1", "ra2e2", "ra2e3", "ra2l1", "ra2l2", "ra2t1",
            // RA4 series
            "ra4c1", "ra4e1", "ra4e2", "ra4l1", "ra4m1", "ra4m2", "ra4m3", "ra4t1", "ra4w1",
            // RA6 series
            "ra6e1", "ra6e2", "ra6m1", "ra6m2", "ra6m3", "ra6m4", "ra6m5", "ra6t1", "ra6t2", "ra6t3",
            // RA8 series
            "ra8d1", "ra8e1", "ra8e2", "ra8m1", "ra8p1", "ra8t1",
        ] {
            println!("cargo::rustc-check-cfg=cfg({})", family);
        }

        generate_memory_x(&out);
        generate_interrupt_bindings(&out);
    }

    println!("cargo:rerun-if-changed=build.rs");
}

/// Generate memory.x linker script
fn generate_memory_x(out: &PathBuf) {
    let mut memory_x = String::new();

    let flash_region = metadata::METADATA.memory.iter().find(|r| r.name == "FLASH").unwrap();
    let mut overlaps = Vec::new();
    for region in metadata::METADATA.memory {
        if region.name.starts_with("OPTION_SETTING_") {
            if region.address >= flash_region.address && region.address < flash_region.address + flash_region.size {
                overlaps.push(region);
            }
        }
    }

    if !overlaps.is_empty() {
        let last_region = overlaps.iter().max_by_key(|r| r.address + r.size).unwrap();
        let end_addr = last_region.address + last_region.size;
        writeln!(memory_x, "_stext = 0x{:08x};", end_addr).unwrap();
    }

    writeln!(memory_x, "MEMORY").unwrap();
    writeln!(memory_x, "{{").unwrap();

    for region in metadata::METADATA.memory {
        let size_str = if region.size >= 1024 && region.size % 1024 == 0 {
            format!("{}K", region.size / 1024)
        } else {
            format!("{}", region.size)
        };

        writeln!(
            memory_x,
            "    {} : ORIGIN = 0x{:08x}, LENGTH = {}",
            region.name, region.address, size_str
        )
        .unwrap();
    }
    writeln!(memory_x, "}}").unwrap();

    writeln!(memory_x, "SECTIONS").unwrap();
    writeln!(memory_x, "{{").unwrap();

    for region in metadata::METADATA.memory {
        if region.name.starts_with("OPTION_SETTING_") {
            let section_name = region.name.strip_prefix("OPTION_SETTING_").unwrap().to_lowercase();
            if overlaps.iter().any(|o| o.name == region.name) {
                writeln!(
                    memory_x,
                    "    .{} 0x{:08x} : {{ KEEP(*(.{})) }} > FLASH",
                    section_name, region.address, section_name
                )
                .unwrap();
            } else {
                writeln!(memory_x, "    .{} : {{ KEEP(*(.{})) }} > {}", section_name, section_name, region.name)
                    .unwrap();
            }
        }
    }
    writeln!(memory_x, "}}").unwrap();

    fs::write(out.join("memory.x"), memory_x).unwrap();
    println!("cargo:rustc-link-search={}", out.display());
    println!("cargo:rerun-if-changed=memory.x");
}

/// Get enabled peripheral configs based on Cargo features
fn get_enabled_configs() -> Vec<&'static PeripheralIrqConfig> {
    get_all_peripheral_configs()
        .into_iter()
        .filter(|config| env::var(format!("CARGO_FEATURE_{}", config.feature)).is_ok())
        .collect()
}

/// Collect all required events from enabled peripherals
fn get_required_events() -> Vec<&'static Event> {
    get_enabled_configs()
        .iter()
        .flat_map(|config| find_events_for_config(config))
        .collect()
}

/// Allocates IRQ slots to events, respecting group constraints
fn allocate_irq_slots(required_events: &[&Event]) -> BTreeMap<&'static str, u8> {
    let mut allocations: BTreeMap<&'static str, u8> = BTreeMap::new();
    let mut used_slots: Vec<bool> = vec![false; metadata::METADATA.interrupt_count];

    // First pass: allocate events with restricted slots (grouped events)
    for event in required_events {
        if !event.irq_slots.is_empty() {
            // Find first available slot from the allowed list
            for &slot in event.irq_slots {
                if !used_slots[slot as usize] {
                    used_slots[slot as usize] = true;
                    allocations.insert(event.name, slot);
                    break;
                }
            }
        }
    }

    // Second pass: allocate events with unrestricted slots
    for event in required_events {
        if allocations.contains_key(event.name) {
            continue; // Already allocated
        }
        if event.irq_slots.is_empty() {
            // Find first available slot
            for (slot, used) in used_slots.iter_mut().enumerate() {
                if !*used {
                    *used = true;
                    allocations.insert(event.name, slot as u8);
                    break;
                }
            }
        }
    }

    allocations
}

/// Generates the interrupt binding code
fn generate_interrupt_bindings(out_dir: &PathBuf) {
    let required_events = get_required_events();
    let allocations = allocate_irq_slots(&required_events);
    let enabled_configs = get_enabled_configs();

    let mut code = String::new();
    writeln!(code, "// Auto-generated interrupt bindings").unwrap();
    writeln!(code, "// DO NOT EDIT - generated by build.rs").unwrap();
    writeln!(code).unwrap();

    // Generate event-to-IRQ mapping constants
    writeln!(code, "/// Auto-allocated IRQ slots for events").unwrap();
    writeln!(code, "pub mod irq_allocations {{").unwrap();
    for (event_name, irq_slot) in &allocations {
        let const_name = event_name.to_uppercase();
        writeln!(code, "    /// IRQ slot for {} event", event_name).unwrap();
        writeln!(code, "    pub const {}_IRQ: u8 = {};", const_name, irq_slot).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Generate event IDs
    writeln!(code, "/// Event IDs for ICU IELSR programming").unwrap();
    writeln!(code, "pub mod event_ids {{").unwrap();
    for event in &required_events {
        let const_name = event.name.to_uppercase();
        writeln!(code, "    pub const {}: u16 = {};", const_name, event.id).unwrap();
    }
    writeln!(code, "}}").unwrap();
    writeln!(code).unwrap();

    // Generate IEL interrupt handlers for each enabled peripheral
    // Group events by handler to generate efficient dispatch
    let mut handler_to_events: BTreeMap<&str, Vec<&Event>> = BTreeMap::new();
    for config in &enabled_configs {
        let events = find_events_for_config(config);
        for event in events {
            handler_to_events
                .entry(config.handler)
                .or_default()
                .push(event);
        }
    }

    // Generate handlers
    for (handler, events) in &handler_to_events {
        for event in events {
            if let Some(&slot) = allocations.get(event.name) {
                writeln!(code, "/// Interrupt handler for {} (IEL{})", event.name, slot).unwrap();
                writeln!(code, "#[no_mangle]").unwrap();
                writeln!(code, "#[allow(non_snake_case)]").unwrap();
                writeln!(code, "pub unsafe extern \"C\" fn IEL{}() {{", slot).unwrap();
                writeln!(code, "    {}();", handler).unwrap();
                writeln!(code, "}}").unwrap();
                writeln!(code).unwrap();
            }
        }
    }

    fs::write(out_dir.join("irq_bindings.rs"), code).unwrap();
}
